### ISSUE TITLE
是MIT协议的吗

### ISSUE THREAD

**Issue by zoxm** [farsunset/lvxin-im#2]
您好，这个项目的[LICENSE](https://github.com/farsunset/lvxin-im/blob/master/LICENSE)是MIT License,但是和信官网中有这些字样，那么这个软件的协议应该怎么处理的呢？
![image](https://user-images.githubusercontent.com/42474721/71861664-0ded4200-3132-11ea-8888-48d93bfab109.png)

**Comment by farsunset** [comment]
侣信并不开源，只是目前提供了安装包供用户安装使用



---原始邮件---
发件人: "zoxm"<notifications@github.com&gt;
发送时间: 2020年1月7日(周二) 上午9:43
收件人: "farsunset/lvxin-im"<lvxin-im@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [farsunset/lvxin-im] 是MIT协议的吗 (#2)



您好，这个项目的LICENSE是MIT License,但是和信官网中有这些字样，那么这个软件的协议应该怎么处理的呢？
